param([switch]$VerifyPreferences)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$projectRoot = Split-Path -Parent $PSScriptRoot
$artifactRoot = [System.IO.Path]::GetFullPath((Join-Path $projectRoot "artifacts\windows"))
$smokeRoot = Join-Path $artifactRoot ("smoke-" + [guid]::NewGuid().ToString("N"))
$editions = @(
    [pscustomobject]@{
        Name = "Player"
        Executable = Join-Path $artifactRoot "player\win-unpacked\Mythic Loot Launcher Player.exe"
        ExpectedTitle = "Mythic Loot Launcher Player"
    },
    [pscustomobject]@{
        Name = "Developer"
        Executable = Join-Path $artifactRoot "developer\win-unpacked\Mythic Loot Launcher Developer.exe"
        ExpectedTitle = "Mythic Loot Launcher Developer"
    }
)

function Stop-SmokeProcess {
    param([Parameter(Mandatory = $true)][System.Diagnostics.Process]$Process)

    if ($Process.HasExited) {
        return
    }
    [void]$Process.CloseMainWindow()
    if (-not $Process.WaitForExit(5000)) {
        Stop-Process -Id $Process.Id -Force
        $Process.WaitForExit()
    }
}

$results = @()
New-Item -ItemType Directory -Path $smokeRoot | Out-Null
try {
    foreach ($edition in $editions) {
        if (-not (Test-Path -LiteralPath $edition.Executable -PathType Leaf)) {
            throw "$($edition.Name) portable executable was not found at $($edition.Executable)"
        }
        $dataRoot = Join-Path $smokeRoot $edition.Name
        New-Item -ItemType Directory -Path $dataRoot | Out-Null
        $env:MYTHIC_LOOT_DATA_DIR = $dataRoot
        $process = Start-Process -FilePath $edition.Executable -PassThru -WindowStyle Hidden
        try {
            $deadline = [DateTime]::UtcNow.AddSeconds(25)
            do {
                Start-Sleep -Milliseconds 250
                $process.Refresh()
            } while (-not $process.HasExited -and $process.MainWindowHandle -eq 0 -and [DateTime]::UtcNow -lt $deadline)

            if ($process.HasExited) {
                throw "$($edition.Name) portable exited with code $($process.ExitCode) before creating a window"
            }
            if ($process.MainWindowHandle -eq 0) {
                throw "$($edition.Name) portable did not create a main window"
            }
            if ($process.MainWindowTitle -ne $edition.ExpectedTitle) {
                throw "$($edition.Name) window title was '$($process.MainWindowTitle)', expected '$($edition.ExpectedTitle)'"
            }
            $configPath = Join-Path $dataRoot "launcher-config.json"
            $configDeadline = [DateTime]::UtcNow.AddSeconds(25)
            do {
                $configCreated = Test-Path -LiteralPath $configPath -PathType Leaf
                if (-not $configCreated) {
                    Start-Sleep -Milliseconds 250
                    $process.Refresh()
                }
            } while (-not $configCreated -and -not $process.HasExited -and [DateTime]::UtcNow -lt $configDeadline)
            if (-not $configCreated) {
                throw "$($edition.Name) did not create isolated launcher configuration"
            }
            $activityPath = Join-Path $dataRoot "activity-history.json"
            $activityDeadline = [DateTime]::UtcNow.AddSeconds(25)
            do {
                $activityCreated = Test-Path -LiteralPath $activityPath -PathType Leaf
                if (-not $activityCreated) {
                    Start-Sleep -Milliseconds 250
                    $process.Refresh()
                }
            } while (-not $activityCreated -and -not $process.HasExited -and [DateTime]::UtcNow -lt $activityDeadline)
            if (-not $activityCreated) {
                throw "$($edition.Name) did not record packaged native startup activity"
            }
            $results += [pscustomobject]@{
                Edition = $edition.Name
                Handle = $process.MainWindowHandle
                Title = $process.MainWindowTitle
                ConfigCreated = $configCreated
                ActivityCreated = $activityCreated
            }
        }
        finally {
            Stop-SmokeProcess -Process $process
        }
        if ($VerifyPreferences) {
            # This is disposable test data generated by the packaged app above,
            # never the user's actual Player/Developer configuration.
            $config = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
            $config.preferences.autoCheckUpdates = $false
            $config.preferences.reduceMotion = $true
            $config.preferences.closeAfterLaunch = $true
            $config.preferences.theme = "slate"
            $config.preferences.font = "verdana"
            $config.preferences.decorativeBackground = $false
            # Migration back to schema 2 proves native bootstrap actually read
            # this configuration before the no-startup-check assertion below.
            $config.schemaVersion = 1
            [System.IO.File]::WriteAllText($configPath, ($config | ConvertTo-Json -Depth 20), (New-Object System.Text.UTF8Encoding($false)))
            if (Test-Path -LiteralPath $activityPath) {
                Move-Item -LiteralPath $activityPath -Destination (Join-Path $dataRoot "first-run-activity.json")
            }
            $preferenceProcess = Start-Process -FilePath $edition.Executable -PassThru -WindowStyle Hidden
            try {
                $deadline = [DateTime]::UtcNow.AddSeconds(25)
                $loaded = $false
                do {
                    Start-Sleep -Milliseconds 250
                    $preferenceProcess.Refresh()
                    if ($preferenceProcess.HasExited) { throw "$($edition.Name) exited during preference acceptance" }
                    try {
                        $saved = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
                        $loaded = $saved.schemaVersion -eq 2
                    } catch { $loaded = $false }
                } while (-not $loaded -and [DateTime]::UtcNow -lt $deadline)
                if (-not $loaded) { throw "$($edition.Name) did not load the isolated preference configuration" }
                Start-Sleep -Seconds 5
                $preferenceProcess.Refresh()
                if ($preferenceProcess.HasExited -or -not $preferenceProcess.Responding -or $preferenceProcess.MainWindowTitle -ne $edition.ExpectedTitle) {
                    throw "$($edition.Name) did not remain responsive after loading preferences"
                }
                $saved = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
                if ($saved.preferences.autoCheckUpdates -or -not $saved.preferences.reduceMotion -or -not $saved.preferences.closeAfterLaunch -or $saved.preferences.theme -ne "slate" -or $saved.preferences.font -ne "verdana" -or $saved.preferences.decorativeBackground) {
                    throw "$($edition.Name) did not preserve the saved preferences"
                }
                if (Test-Path -LiteralPath $activityPath) {
                    $activity = Get-Content -LiteralPath $activityPath -Raw | ConvertFrom-Json
                    $checks = @($activity.items | Where-Object { $_.kind -eq "catalogue" -or $_.kind -eq "appUpdate" })
                    if ($checks.Count -ne 0) { throw "$($edition.Name) started update checks despite the disabled preference" }
                }
                Write-Host "$($edition.Name): packaged bootstrap preserved preferences and did not start catalogue/app update checks."
            }
            finally {
                Stop-SmokeProcess -Process $preferenceProcess
            }
        }
    }
}
finally {
    Remove-Item Env:MYTHIC_LOOT_DATA_DIR -ErrorAction SilentlyContinue
    $resolvedSmokeRoot = [System.IO.Path]::GetFullPath($smokeRoot)
    if (-not $resolvedSmokeRoot.StartsWith($artifactRoot + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Smoke cleanup target escaped the Windows artifacts directory: $resolvedSmokeRoot"
    }
    if (Test-Path -LiteralPath $resolvedSmokeRoot -PathType Container) {
        Remove-Item -LiteralPath $resolvedSmokeRoot -Recurse -Force
    }
}

$results | Format-Table -AutoSize
Write-Host "Both portable Windows editions passed isolated responsive-window and native-activity smoke acceptance."
